CREATE DATABASE BODEGASBD;
USE BODEGASBD;

CREATE TABLE TIPOPRODUCTO(
IDTIPOPRODUCTO INT NOT NULL,
NOMBRE VARCHAR(100)
);
ALTER TABLE TIPOPRODUCTO ADD PRIMARY KEY(IDTIPOPRODUCTO);

CREATE TABLE PRODUCTO(
IDPRODUCTO INT NOT NULL,
NOMBRE VARCHAR(100),
DESCRIPCION VARCHAR(255),
PRECIO DOUBLE,
EXISTENCIA INT,
IDTIPOPRODUCTO INT
);
ALTER TABLE PRODUCTO ADD PRIMARY KEY (IDPRODUCTO);
ALTER TABLE PRODUCTO ADD CONSTRAINT FK_PRODUCTOTIPO FOREIGN KEY (IDTIPOPRODUCTO) REFERENCES TIPOPRODUCTO(IDTIPOPRODUCTO);

CREATE TABLE CLIENTE(
IDCLIENTE INT NOT NULL,
NOMBRE VARCHAR(50),
APELLIDO VARCHAR(50)
);
ALTER TABLE CLIENTE ADD PRIMARY KEY(IDCLIENTE);

CREATE TABLE TELEFONOC(
IDTELEFONOC INT NOT NULL,
IDCLIENTE INT NOT NULL,
NUMERO INT
);
ALTER TABLE TELEFONOC ADD PRIMARY KEY (IDTELEFONOC);
ALTER TABLE TELEFONOC ADD CONSTRAINT FK_TELEFONOCLIENTE FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE);

CREATE TABLE PROVEEDOR(
IDPROVEEDOR INT NOT NULL,
NOMBRE VARCHAR(50),
DIRECCION VARCHAR(255)
);
ALTER TABLE PROVEEDOR ADD PRIMARY KEY(IDPROVEEDOR);

CREATE TABLE TELEFONOP(
IDTELEFONOP INT NOT NULL,
IDPROVEEDOR INT NOT NULL,
NUMERO INT
);
ALTER TABLE TELEFONOP ADD PRIMARY KEY (IDTELEFONOP);
ALTER TABLE TELEFONOP ADD CONSTRAINT FK_TELEFONOPROVEEDOR FOREIGN KEY (IDPROVEEDOR) REFERENCES PROVEEDOR(IDPROVEEDOR);

CREATE TABLE TIPOEMPLEADO(
IDTIPOEMPLEADO INT NOT NULL,
NOMBRE VARCHAR(50)
);
ALTER TABLE TIPOEMPLEADO ADD PRIMARY KEY(IDTIPOEMPLEADO);

CREATE TABLE EMPLEADO(
IDEMPLEADO INT NOT NULL,
NOMBRE VARCHAR(50),
APELLIDO VARCHAR(50),
FECHACONTRATACION DATETIME,
IDTIPOEMPLEADO INT NOT NULL
);
ALTER TABLE EMPLEADO ADD PRIMARY KEY (IDEMPLEADO);
ALTER TABLE EMPLEADO ADD CONSTRAINT FK_EMPLEADOTIPO FOREIGN KEY (IDTIPOEMPLEADO) REFERENCES TIPOEMPLEADO(IDTIPOEMPLEADO);

CREATE TABLE TELEFONOE(
IDTELEFONOE INT NOT NULL,
IDEMPLEADO INT NOT NULL,
NUMERO INT
);
ALTER TABLE TELEFONOE ADD PRIMARY KEY (IDTELEFONOE);
ALTER TABLE TELEFONOE ADD CONSTRAINT FK_TELEFONOEMPLEADO FOREIGN KEY (IDEMPLEADO) REFERENCES EMPLEADO(IDEMPLEADO);

CREATE TABLE FACTURAENCABEZADOC(
IDFACTURAENCABEZADOC INT NOT NULL,
FECHA DATETIME,
IDCLIENTE INT NOT NULL,
IDEMPLEADO INT NOT NULL,
ESTATUS TINYINT
);
ALTER TABLE FACTURAENCABEZADOC ADD PRIMARY KEY (IDFACTURAENCABEZADOC);
ALTER TABLE FACTURAENCABEZADOC ADD CONSTRAINT FK_ENCABEZADOCLIENTE FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE);
ALTER TABLE FACTURAENCABEZADOC ADD CONSTRAINT FK_ENCABEZADOEMPLEADO FOREIGN KEY (IDEMPLEADO) REFERENCES EMPLEADO(IDEMPLEADO);

CREATE TABLE FACTURADETALLEC(
IDFACTURAENCABEZADOC INT NOT NULL,
IDPRODUCTO INT NOT NULL,
CANTIDAD INT
);
ALTER TABLE FACTURADETALLEC ADD PRIMARY KEY (IDFACTURAENCABEZADOC, IDPRODUCTO);
ALTER TABLE FACTURADETALLEC ADD CONSTRAINT FK_DETALLEENCABEZADO FOREIGN KEY (IDFACTURAENCABEZADOC) REFERENCES FACTURAENCABEZADOC(IDFACTURAENCABEZADOC); 
ALTER TABLE FACTURADETALLEC ADD CONSTRAINT FK_PRODUCTODETALLE FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTO(IDPRODUCTO);

CREATE TABLE FACTURAENCABEZADOCR(
IDFACTURAENCABEZADOCR INT NOT NULL,
FECHA DATETIME,
IDCLIENTE INT NOT NULL,
IDEMPLEADO INT NOT NULL,
ESTATUS TINYINT,
PLAZODIAS INT
);
ALTER TABLE FACTURAENCABEZADOCR ADD PRIMARY KEY (IDFACTURAENCABEZADOCR);
ALTER TABLE FACTURAENCABEZADOCR ADD CONSTRAINT FK_ENCABEZADOCRCLIENTE FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE);
ALTER TABLE FACTURAENCABEZADOCR ADD CONSTRAINT FK_ENCABEZADOCREMPLEADO FOREIGN KEY (IDEMPLEADO) REFERENCES EMPLEADO(IDEMPLEADO);

CREATE TABLE FACTURADETALLECR(
IDFACTURAENCABEZADOCR INT NOT NULL,
IDPRODUCTO INT NOT NULL,
CANTIDAD INT
);
ALTER TABLE FACTURADETALLECR ADD PRIMARY KEY (IDFACTURAENCABEZADOCR, IDPRODUCTO);
ALTER TABLE FACTURADETALLECR ADD CONSTRAINT FK_DETALLEENCABEZADOCR FOREIGN KEY (IDFACTURAENCABEZADOCR) REFERENCES FACTURAENCABEZADOCR(IDFACTURAENCABEZADOCR); 
ALTER TABLE FACTURADETALLECR ADD CONSTRAINT FK_PRODUCTODETALLECR FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTO(IDPRODUCTO);

CREATE TABLE COBRO(
IDCOBRO INT NOT NULL,
FECHA DATETIME,
IDFACTURAENCABEZADOCR INT NOT NULL,
IDEMPLEADO INT NOT NULL
);
ALTER TABLE COBRO ADD PRIMARY KEY (IDCOBRO);
ALTER TABLE COBRO ADD CONSTRAINT FK_COBROFACTURA FOREIGN KEY (IDFACTURAENCABEZADOCR) REFERENCES FACTURAENCABEZADOCR(IDFACTURAENCABEZADOCR); 
ALTER TABLE COBRO ADD CONSTRAINT FK_COBROEMPLEADO FOREIGN KEY (IDEMPLEADO) REFERENCES EMPLEADO(IDEMPLEADO);

CREATE TABLE TIPOCOMISION(
IDTIPOCOMISION INT NOT NULL,
NOMBRE VARCHAR(50)
);
ALTER TABLE TIPOCOMISION ADD PRIMARY KEY (IDTIPOCOMISION);

CREATE TABLE COMISION(
IDCOMISION INT NOT NULL,
IDEMPLEADO INT NOT NULL,
IDTIPOCOMISION INT NOT NULL,
MONTO DOUBLE
);
ALTER TABLE COMISION ADD PRIMARY KEY (IDCOMISION);
ALTER TABLE COMISION ADD CONSTRAINT FK_COMISIONEMPLEADO FOREIGN KEY (IDEMPLEADO) REFERENCES EMPLEADO(IDEMPLEADO);
ALTER TABLE COMISION ADD CONSTRAINT FK_COMISIONTIPO FOREIGN KEY (IDTIPOCOMISION) REFERENCES TIPOCOMISION(IDTIPOCOMISION);

CREATE TABLE COMPRAENCABEZADO(
IDCOMPRAENCABEZADO INT NOT NULL,
FECHA DATETIME,
IDPROVEEDOR INT NOT NULL,
IDEMPLEADO INT NOT NULL,
ESTATUS TINYINT
);
ALTER TABLE COMPRAENCABEZADO ADD PRIMARY KEY (IDCOMPRAENCABEZADO);
ALTER TABLE COMPRAENCABEZADO ADD CONSTRAINT FK_COMPRAENCABEZADOPROVEEDOR FOREIGN KEY (IDPROVEEDOR) REFERENCES PROVEEDOR(IDPROVEEDOR);
ALTER TABLE COMPRAENCABEZADO ADD CONSTRAINT FK_COMPRAENCABEZADOEMPLEADO FOREIGN KEY (IDEMPLEADO) REFERENCES EMPLEADO(IDEMPLEADO);

CREATE TABLE COMPRADETALLE(
IDCOMPRAENCABEZADO INT NOT NULL,
IDPRODUCTO INT NOT NULL,
CANTIDAD INT
);
ALTER TABLE COMPRADETALLE ADD PRIMARY KEY (IDCOMPRAENCABEZADO, IDPRODUCTO);
ALTER TABLE COMPRADETALLE ADD CONSTRAINT FK_DETALLEENCABEZADOCOMPRA FOREIGN KEY (IDCOMPRAENCABEZADO) REFERENCES COMPRAENCABEZADO(IDCOMPRAENCABEZADO); 
ALTER TABLE COMPRADETALLE ADD CONSTRAINT FK_PRODUCTODETALLECOMPRA FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTO(IDPRODUCTO);

/**/
CREATE TABLE COTIZACIONENCABEZADO(
IDCOTIZACIONENCABEZADO INT NOT NULL,
FECHA DATETIME,
FECHAVENCIMIENTO DATETIME,
IDEMPLEADO INT NOT NULL
);
ALTER TABLE COTIZACIONENCABEZADO ADD PRIMARY KEY (IDCOTIZACIONENCABEZADO);
ALTER TABLE COTIZACIONENCABEZADO ADD CONSTRAINT FK_COTIZACIONENCABEZADOEMPLEADO FOREIGN KEY (IDEMPLEADO) REFERENCES EMPLEADO(IDEMPLEADO);

CREATE TABLE COTIZACIONDETALLE(
IDCOTIZACIONENCABEZADO INT NOT NULL,
IDPRODUCTO INT NOT NULL,
CANTIDAD INT
);
ALTER TABLE COTIZACIONDETALLE ADD PRIMARY KEY (IDCOTIZACIONENCABEZADO, IDPRODUCTO);
ALTER TABLE COTIZACIONDETALLE ADD CONSTRAINT FK_DETALLEENCABEZADOCOTI FOREIGN KEY (IDCOTIZACIONENCABEZADO) REFERENCES COTIZACIONDETALLE(IDCOTIZACIONENCABEZADO); 
ALTER TABLE COTIZACIONDETALLE ADD CONSTRAINT FK_PRODUCTODETALLECOTI FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTO(IDPRODUCTO);

/**/
CREATE TABLE PEDIDOENCABEZADO(
IDPEDIDOENCABEZADO INT NOT NULL,
FECHA DATETIME,
IDCLIENTE INT NOT NULL
);
ALTER TABLE PEDIDOENCABEZADO ADD PRIMARY KEY (IDPEDIDOENCABEZADO);
ALTER TABLE PEDIDOENCABEZADO ADD CONSTRAINT FK_PEDIDOCLIENTE FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE);

CREATE TABLE PEDIDODETALLE(
IDPEDIDOENCABEZADO INT NOT NULL,
IDPRODUCTO INT NOT NULL,
CANTIDAD INT
);
ALTER TABLE PEDIDODETALLE ADD PRIMARY KEY (IDPEDIDOENCABEZADO, IDPRODUCTO);
ALTER TABLE PEDIDODETALLE ADD CONSTRAINT FK_DETALLEENCABEZADOPEDIDO FOREIGN KEY (IDPEDIDOENCABEZADO) REFERENCES PEDIDOENCABEZADO(IDPEDIDOENCABEZADO); 
ALTER TABLE PEDIDODETALLE ADD CONSTRAINT FK_PRODUCTODETALLEPEDIDO FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTO(IDPRODUCTO);


CREATE TABLE PRODUCTO(
IDPRODUCTO INT NOT NULL,
NOMBRE VARCHAR(100),
DESCRIPCION VARCHAR(255),
PRECIO DOUBLE,
EXISTENCIA INT,
IDTIPOPRODUCTO INT
);
ALTER TABLE PRODUCTO ADD PRIMARY KEY (IDPRODUCTO);
ALTER TABLE PRODUCTO ADD CONSTRAINT FK_PRODUCTOTIPO FOREIGN KEY (IDTIPOPRODUCTO) REFERENCES TIPOPRODUCTO(IDTIPOPRODUCTO);

INSERT INTO TIPOPRODUCTO VALUES (1,'ABONOS');
INSERT INTO TIPOPRODUCTO VALUES (2,'LIMPIEZA');
INSERT INTO TIPOPRODUCTO VALUES (3,'CEREALES');

INSERT INTO PRODUCTO VALUES(1,'SHAMPOO','LIQUIDO PARA BALAR ANIMALES',25.50, 50,2);
INSERT INTO PRODUCTO VALUES(2,'CEREAL PURINA','EXTRACTO DE CARNE Y POLLO',50, 50,3);
INSERT INTO PRODUCTO VALUES(3,'FERTILIZANTE','PARA HACER QUE LA TIERRA ESTE BIEN',10, 25,1);